server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: suricata
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          __path__: /var/log/suricata/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            src_ip: src_ip
            dest_ip: dest_ip
            alert: alert
      - labels:
          event_type:
          src_ip:
          dest_ip:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
