server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: snort
    static_configs:
      - targets:
          - localhost
        labels:
          job: snort
          __path__: /var/log/snort/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{2}/\d{2}-\d{2}:\d{2}:\d{2}\.\d+)\s+\[\*\*\]\s+\[(?P<gid>\d+):(?P<sid>\d+):(?P<rev>\d+)\]\s+(?P<msg>.*?)\s+\[\*\*\].*?(?P<src_ip>\d+\.\d+\.\d+\.\d+)(?::(?P<src_port>\d+))?\s+->\s+(?P<dest_ip>\d+\.\d+\.\d+\.\d+)(?::(?P<dest_port>\d+))?'
      - labels:
          gid:
          sid:
          src_ip:
          dest_ip:
          msg:
      - timestamp:
          source: timestamp
          format: "01/02-15:04:05.000000"
